baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CNCF Landscape Overview'
theme = 'cncf-theme'
buildFuture = true
dataDir = '../data'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
